# Generated by Django 4.1.7 on 2023-02-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_task_rename_user_card_task_rename_prompt_card_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.task'),
        ),
    ]
