# Generated by Django 4.1.7 on 2023-03-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='completion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
