# Generated by Django 4.1.7 on 2023-04-02 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.board'),
            preserve_default=False,
        ),
    ]
