# Generated by Django 4.1.7 on 2023-02-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarduser',
            name='openai_secret',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
