# Generated by Django 4.1.7 on 2023-03-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_boarduser_openai_secret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boarduser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='boarduser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='boarduser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='boarduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='boarduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='boarduser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='boarduser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='boarduser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='boarduser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='boarduser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='boarduser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='boarduser',
            name='username',
        ),
    ]
