# Generated by Django 4.1.7 on 2023-03-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_boarduser_options_alter_boarduser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarduser',
            name='openai_secret',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
